#!/usr/bin/env python3
"""Build the canonical mean-field peeling PDF from maintained Markdown.

The workspace's TeX Live 2022 ``markdown`` package predates native support for
dollar-delimited mathematics. This script protects each Markdown math span as
raw TeX, verifies that every delimiter was consumed exactly once, compiles the
single report wrapper from an ignored build directory, and copies the checked
PDF to the study directory.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path


REPORT_DIR = Path(__file__).resolve().parent
STUDY_DIR = REPORT_DIR.parent
BUILD_DIR = REPORT_DIR / "build"
MARKDOWN_DIR = BUILD_DIR / "markdown"
REPORT_TEX = REPORT_DIR / "MEAN_FIELD_PEELING_REPORT.tex"
REPORT_PDF = REPORT_DIR / "MEAN_FIELD_PEELING_REPORT.pdf"

SOURCES = (
    STUDY_DIR / "CURRENT_RESEARCH_STATE.md",
    STUDY_DIR / "MUP_TRAINING_CASE_STUDY.md",
    STUDY_DIR / "archive" / "ORIGINAL_NOTES_AND_NTK_SAMPLE.md",
)

DISPLAY_MATH = re.compile(
    r"(?ms)^([ \t]*(?:>[ \t]*)?)\$\$[ \t]*\n?(.*?)\n?\1\$\$[ \t]*$"
)
INLINE_MATH = re.compile(r"(?<!\\)\$(?!\$)(.+?)(?<!\\)\$(?!\$)")
UNESCAPED_DOLLAR = re.compile(r"(?<!\\)\$")
LOCAL_LINK = re.compile(r"(?<!!)\[([^\]\n]+)\]\((?!https?://)[^)]+\)")


def run(command: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if completed.returncode != 0:
        tail = "\n".join(completed.stdout.splitlines()[-120:])
        raise RuntimeError(
            f"Command failed with exit code {completed.returncode}: "
            f"{' '.join(command)}\n{tail}"
        )
    return completed


def protect_markdown() -> int:
    mathematics: list[tuple[str, str]] = []

    def register(kind: str, body: str) -> str:
        mathematics.append((kind, body.strip()))
        return rf"\MFMath{{{len(mathematics)}}}"

    for source_path in SOURCES:
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing canonical source: {source_path}")

        source = source_path.read_text(encoding="utf-8")

        # The legacy LaTeX Markdown renderer turns links into URL footnotes and
        # cannot safely pass GitHub-style ``#fragment`` targets to hyperref.
        # Preserve canonical links in the source files, but render local file
        # and section links as their visible text in the PDF-generated copies.
        # External HTTP(S) citations remain links and are handled by the TeX
        # wrapper's inline hyperlink renderer.
        source = LOCAL_LINK.sub(r"\1", source)

        def replace_display(match: re.Match[str]) -> str:
            prefix, body = match.group(1), match.group(2)
            if ">" in prefix:
                body = "\n".join(
                    line[len(prefix) :] if line.startswith(prefix) else line
                    for line in body.splitlines()
                )
            return prefix + register("display", body)

        protected = DISPLAY_MATH.sub(replace_display, source)
        protected = INLINE_MATH.sub(
            lambda match: register("inline", match.group(1)), protected
        )

        residual = list(UNESCAPED_DOLLAR.finditer(protected))
        if residual:
            offsets = ", ".join(str(match.start()) for match in residual[:10])
            raise ValueError(
                f"Unprotected dollar delimiter in {source_path.name} at "
                f"offset(s) {offsets}"
            )

        output_name = source_path.stem + ".pdf.md"
        (MARKDOWN_DIR / output_name).write_text(protected, encoding="utf-8")

    definitions = [
        "% Generated by build_report.py; do not edit.",
        r"\newcommand{\MFMath}[1]{\csname MFmath#1\endcsname}",
    ]
    for index, (kind, body) in enumerate(mathematics, start=1):
        body = body.replace("#", r"\#")
        if kind == "display":
            rendered = "\\[\n" + body + "\n\\]"
        else:
            rendered = r"\ensuremath{" + body + "}"
        definitions.append(
            rf"\expandafter\def\csname MFmath{index}\endcsname{{{rendered}}}"
        )

    definitions_path = MARKDOWN_DIR / "markdown_math_defs.tex"
    definitions_path.write_text("\n".join(definitions) + "\n", encoding="utf-8")

    placeholders = 0
    for source_path in SOURCES:
        generated = MARKDOWN_DIR / (source_path.stem + ".pdf.md")
        placeholders += len(re.findall(r"\\MFMath\{\d+\}", generated.read_text()))

    if placeholders != len(mathematics):
        raise RuntimeError(
            f"Math protection mismatch: {len(mathematics)} definitions but "
            f"{placeholders} placeholders"
        )

    ids = [int(value) for value in re.findall(r"\\MFMath\{(\d+)\}", "".join(
        (MARKDOWN_DIR / (path.stem + ".pdf.md")).read_text()
        for path in SOURCES
    ))]
    expected_ids = list(range(1, len(mathematics) + 1))
    if sorted(ids) != expected_ids:
        raise RuntimeError(
            "Math placeholder identifiers are missing, duplicated, or out of range"
        )

    return len(mathematics)


def compile_report() -> Path:
    if shutil.which("latexmk") is None or shutil.which("xelatex") is None:
        raise RuntimeError("latexmk and xelatex are required to build the report")

    run(
        [
            "latexmk",
            "-xelatex",
            "-shell-escape",
            "-interaction=nonstopmode",
            "-halt-on-error",
            "-file-line-error",
            f"../{REPORT_TEX.name}",
        ],
        cwd=BUILD_DIR,
    )
    built_pdf = BUILD_DIR / REPORT_PDF.name
    if not built_pdf.is_file() or built_pdf.stat().st_size == 0:
        raise RuntimeError(f"Expected PDF was not created: {built_pdf}")

    log_path = BUILD_DIR / REPORT_TEX.with_suffix(".log").name
    log = log_path.read_text(encoding="utf-8", errors="replace")
    fatal_markers = (
        "LaTeX Error:",
        "Undefined control sequence",
        "Missing $ inserted",
        "Emergency stop",
        "Fatal error",
    )
    found = [marker for marker in fatal_markers if marker in log]
    if found:
        raise RuntimeError(f"Fatal LaTeX marker(s) in build log: {found}")

    if shutil.which("qpdf") is not None:
        run(["qpdf", "--check", str(built_pdf)], cwd=BUILD_DIR)

    return built_pdf


def verify_pdf(pdf_path: Path) -> None:
    if shutil.which("pdftotext") is None:
        return

    extracted = run(["pdftotext", str(pdf_path), "-"], cwd=BUILD_DIR).stdout
    normalized = re.sub(r"\s+", " ", extracted)
    sentinels = (
        "Mean-Field Peeling: Theory, Algorithm, and Theorem Program",
        "Target Mean-Field Derivative Peeling Theorem",
        "Case Study: Mean-Field Peeling",
        "Complete two-sample five-branch backward audit",
        "Execution III: two gradient-descent steps",
        "Original Mean-Field Peeling Notes and NTK Sample",
        "Current archival status",
    )
    missing = [sentinel for sentinel in sentinels if sentinel not in normalized]
    if missing:
        raise RuntimeError(f"PDF semantic sentinel(s) missing: {missing}")


def main() -> None:
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    MARKDOWN_DIR.mkdir(parents=True)

    math_count = protect_markdown()
    print(f"Protected {math_count} math spans from {len(SOURCES)} sources.")

    built_pdf = compile_report()
    verify_pdf(built_pdf)
    shutil.copy2(built_pdf, REPORT_PDF)
    print(f"Wrote {REPORT_PDF}")


if __name__ == "__main__":
    main()
