<h2 class="sr-only">Figure 15c. The Legendre moment model, restarted from q moments of the dense past, generates its own future; it follows the dense network's future when q is large enough.</h2>
<div style="font-size:15px;font-weight:500;color:var(--text-primary);margin:0 0 8px">Figure 15c · Moments are enough to continue</div>
<div id="ctl" style="display:flex;flex-wrap:wrap;align-items:center;gap:6px 14px;margin:0 0 8px;font-size:13px;color:var(--text-secondary)"></div>
<svg id="sv" width="100%" viewBox="0 0 680 515" role="img"><title>Figure 15c: moments are enough to continue</title><desc>Phase plane and time series of a real forward and backward history; the memory from q moments of the past; the future generated by the restarted moment model; the dense future; test output error of the restarted model.</desc>
<defs><clipPath id="k1"><rect x="44" y="40" width="296" height="262"/></clipPath><clipPath id="k2"><rect x="392" y="36" width="270" height="120"/></clipPath><clipPath id="k3"><rect x="392" y="190" width="270" height="112"/></clipPath></defs>
<g id="g1" clip-path="url(#k1)"></g><g id="g2" clip-path="url(#k2)"></g><g id="g3" clip-path="url(#k3)"></g><g id="g4"></g></svg>
<script>
(()=>{
const D=__DATA__;
const dec=(v,r)=>v.map(k=>r[0]+(r[1]-r[0])*k/999);D.links.forEach(L=>{L.x=dec(L.x,L.rx);L.y=dec(L.y,L.ry);L.W=dec(L.W,L.rw);L.fut.forEach(fr=>fr.forEach(f=>{f.x=dec(f.x,L.rx);f.y=dec(f.y,L.ry);f.W=dec(f.W,L.rw)}))});
const BL='#2a78d6',BD='#185FA5',PU='#7F77DD',PD='#534AB7',GR='#888780',NG=D.tau.length;
let li=0,ri=1,qi=2,reveal=1,anim=null;
const ctl=document.getElementById('ctl');
function group(label,items,get,set){const w=document.createElement('span');w.style.cssText='display:flex;align-items:center;gap:4px';w.appendChild(Object.assign(document.createElement('span'),{textContent:label}));
items.forEach((t,k)=>{const b=document.createElement('button');b.textContent=t;b.style.cssText='font-size:13px;padding:3px 9px';b.onclick=()=>{set(k);sync();replay()};b.dataset.k=k;w.appendChild(b)});w.dataset.g=label;ctl.appendChild(w);return ()=>{[...w.querySelectorAll('button')].forEach(b=>{const on=+b.dataset.k===get();b.style.borderColor=on?BL:'';b.style.color=on?BL:'';b.style.fontWeight=on?500:400})}}
const syncs=[group('Link',['A','B','C'],()=>li,k=>li=k),group('Restart at t =',D.restarts.map(r=>String(r.t)),()=>ri,k=>ri=k),group('Moments q =',D.restarts[0].orders.map(String),()=>qi,k=>qi=k)];
const rb=document.createElement('button');rb.textContent='Replay';rb.style.cssText='font-size:13px;padding:3px 9px';rb.onclick=replay;ctl.appendChild(rb);
const sync=()=>syncs.forEach(f=>f());
const at=(arr,s)=>{const f=s/D.tauEnd*(NG-1),i=Math.max(0,Math.min(NG-2,Math.floor(f))),w=f-i;return arr[i]*(1-w)+arr[i+1]*w};
const leg=(x,q)=>{const P=[1,x];for(let j=1;j<q;j++)P.push(((2*j+1)*x*P[j]-j*P[j-1])/(j+1));return P};
function memory(L,s,q){const M=500,cx=Array(q).fill(0),cy=Array(q).fill(0);for(let k=0;k<=M;k++){const u=s*k/M,w=(k===0||k===M?0.5:1)*s/M,P=leg(2*u/s-1,q),xv=at(L.x,u),yv=at(L.y,u);for(let j=0;j<q;j++){cx[j]+=w*P[j]*xv;cy[j]+=w*P[j]*yv}}
const c=cx.map((v,j)=>[(2*j+1)/s*v,(2*j+1)/s*cy[j]]),out=[];for(let k=0;k<=160;k++){const u=s*k/160,P=leg(2*u/s-1,q);let a=0,b=0;for(let j=0;j<q;j++){a+=c[j][0]*P[j];b+=c[j][1]*P[j]}out.push([u,a,b])}return out}
const seg=(pts,attr)=>{if(pts.length<2)return '';let d='';pts.forEach((p,k)=>{d+=(k?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)});return `<path d="${d}" fill="none" ${attr}/>`};
function draw(){const L=D.links[li],R=D.restarts[ri],q=R.orders[qi],s=R.tauR,F=L.fut[ri][qi],mem=memory(L,s,q);
const allMem=R.orders.map(qq=>memory(L,s,qq)),xs=[...L.x],ys=[...L.y];L.fut[ri].forEach(f=>{xs.push(...f.x);ys.push(...f.y)});allMem.forEach(mm=>mm.forEach(p=>{xs.push(p[1]);ys.push(p[2])}));
const xmn=Math.min(...xs),xmx=Math.max(...xs),ymn=Math.min(...ys),ymx=Math.max(...ys),px=v=>54+276*(v-xmn)/(xmx-xmn),py=v=>292-244*(v-ymn)/(ymx-ymn);
const nF=Math.max(2,Math.round(reveal*F.tau.length));
let a='';const past=[];for(let k=0;k<=160;k++){const u=s*k/160;past.push([px(at(L.x,u)),py(at(L.y,u)),u])}
for(let k=0;k<160;k++){const op=0.25+0.55*Math.exp(-(s-past[k+1][2])/2.2);a+=`<line x1="${past[k][0].toFixed(1)}" y1="${past[k][1].toFixed(1)}" x2="${past[k+1][0].toFixed(1)}" y2="${past[k+1][1].toFixed(1)}" stroke="${GR}" stroke-width="2.4" stroke-linecap="round" opacity="${op.toFixed(3)}"/>`}
const fu=[];for(let k=0;k<=100;k++){const u=s+(D.tauEnd-s)*k/100;fu.push([px(at(L.x,u)),py(at(L.y,u))])}a+=seg(fu,`stroke="${GR}" stroke-width="8" stroke-linecap="round" opacity="0.22"`);
a+=q===1?`<circle cx="${px(mem[0][1]).toFixed(1)}" cy="${py(mem[0][2]).toFixed(1)}" r="6" fill="none" stroke="${BL}" stroke-width="1.8" stroke-dasharray="3 2"/>`:seg(mem.map(p=>[px(p[1]),py(p[2])]),`stroke="${BL}" stroke-width="1.8" stroke-dasharray="6 4"`);
const mf=F.x.slice(0,nF).map((v,k)=>[px(v),py(F.y[k])]);a+=seg(mf,`stroke="${BD}" stroke-width="2.6" stroke-linecap="round"`);
a+=`<circle cx="${px(at(L.x,s)).toFixed(1)}" cy="${py(at(L.y,s)).toFixed(1)}" r="5" fill="var(--p)"/>`;
if(reveal>=1){a+=`<circle cx="${px(F.x[F.x.length-1]).toFixed(1)}" cy="${py(F.y[F.y.length-1]).toFixed(1)}" r="4" fill="none" stroke="${BD}" stroke-width="2"/><circle cx="${px(L.x[NG-1]).toFixed(1)}" cy="${py(L.y[NG-1]).toFixed(1)}" r="2.5" fill="${GR}"/>`}
document.getElementById('g1').innerHTML=a;
const tx=u=>396+262*u/D.tauEnd,hn=v=>(v-xmn)/(xmx-xmn),bn=v=>(v-ymn)/(ymx-ymn),hy=v=>146-104*v;
let b=`<line x1="${tx(s)}" y1="36" x2="${tx(s)}" y2="156" stroke="${GR}" stroke-width="0.8" stroke-dasharray="2 3"/>`;
[[L.x,hn,BL,BD,1,F.x],[L.y,bn,PU,PD,2,F.y]].forEach(([arr,nm,c1,c2,ci,fut])=>{const pa=[],pf=[];for(let k=0;k<NG;k++){const u=D.tau[k];(u<=s?pa:pf).push([tx(u),hy(nm(arr[k]))])}
b+=seg(pa,`stroke="${c1}" stroke-width="1.3"`)+seg(pf,`stroke="${GR}" stroke-width="7" stroke-linecap="round" opacity="0.22"`)+seg(mem.map(p=>[tx(p[0]),hy(nm(p[ci]))]),`stroke="${c1}" stroke-width="1.8" stroke-dasharray="5 3"`)+seg(fut.slice(0,nF).map((v,k)=>[tx(F.tau[k]),hy(nm(v))]),`stroke="${c2}" stroke-width="2.4"`)});
document.getElementById('g2').innerHTML=b;
const Wall=[...L.W];L.fut[ri].forEach(f=>Wall.push(...f.W));const wmn=Math.min(0,...Wall),wmx=Math.max(...Wall),wy=v=>296-100*(v-wmn)/(wmx-wmn);
let w=`<line x1="${tx(s)}" y1="190" x2="${tx(s)}" y2="302" stroke="${GR}" stroke-width="0.8" stroke-dasharray="2 3"/>`;const wp=[],wf=[];for(let k=0;k<NG;k++){const u=D.tau[k];(u<=s?wp:wf).push([tx(u),wy(L.W[k])])}
w+=seg(wp,`stroke="var(--p)" stroke-width="1.6"`)+seg(wf,`stroke="${GR}" stroke-width="7" stroke-linecap="round" opacity="0.22"`)+seg(F.W.slice(0,nF).map((v,k)=>[tx(F.tau[k]),wy(v)]),`stroke="${BD}" stroke-width="2.4"`);
document.getElementById('g3').innerHTML=w;
let z=`<text x="40" y="22" class="th">Link ${'ABC'[li]}: ${L.name}</text><text x="48" y="318" class="ts">forward hⱼ →</text><text x="48" y="36" class="ts">↑ backward bᵢ</text>`;
z+=`<text x="392" y="22" class="th">Both histories on the clock τ</text><text x="396" y="170" class="ts">blue: forward · purple: backward</text>`;
z+=`<text x="392" y="184" class="th">The weight Wᵢⱼ</text><text x="396" y="318" class="ts">black/gray: dense · bold: moment model</text>`;
const EX0=60,EW=560,EY0=362,EH=96,t0=R.t,ex=t=>EX0+EW*(t-t0)/(32-t0),ey=v=>EY0+EH*Math.min(1,Math.max(0,(-1-Math.log10(Math.max(v,1e-7)))/5));
z+=`<text x="40" y="348" class="th">After restart: all 30 test outputs of the moment model vs the dense network</text>`;
z+=`<line x1="${EX0}" y1="${EY0+EH}" x2="${EX0+EW}" y2="${EY0+EH}" stroke="var(--b)" stroke-width="0.5"/><line x1="${EX0}" y1="${EY0}" x2="${EX0}" y2="${EY0+EH}" stroke="var(--b)" stroke-width="0.5"/>`;
R.err.forEach((e,k)=>{const on=k===qi,n2=on?Math.max(2,Math.round(reveal*e.length)):e.length;z+=seg(e.slice(0,n2).map((v,j)=>[ex(R.tq[j]),ey(v)]),`stroke="${on?BD:GR}" stroke-width="${on?2.4:1}" opacity="${on?1:0.6}"`);z+=`<text x="${EX0+EW+6}" y="${ey(e[e.length-1])+4}" class="ts">q=${R.orders[k]}</text>`});
[[1e-1,'0.1'],[1e-3,'0.001'],[1e-5,'1e-5']].forEach(([v,lab])=>z+=`<text x="${EX0-6}" y="${ey(v)+4}" text-anchor="end" class="ts">${lab}</text>`);
z+=`<text x="${EX0}" y="${EY0+EH+16}" class="ts">t = ${t0}</text><text x="${EX0+EW}" y="${EY0+EH+16}" text-anchor="end" class="ts">t = 32</text><text x="${EX0+EW/2}" y="${EY0+EH+16}" text-anchor="middle" class="ts">test RMS difference (log)</text>`;
z+=`<text x="40" y="490" class="ts">gray line: dense past (fading) · wide gray band: dense future · dashed: memory from q moments</text><text x="40" y="507" class="ts">bold: the future computed by the moment model alone, restarted from its q moments</text>`;
document.getElementById('g4').innerHTML=z}
function replay(){if(anim)cancelAnimationFrame(anim);const st=performance.now();const tick=n=>{reveal=Math.min(1,(n-st)/2200);draw();if(reveal<1)anim=requestAnimationFrame(tick)};anim=requestAnimationFrame(tick)}
sync();draw();
})();
</script>