project:
  type: book

book:
  title: "PDE: population dynamics of deep learning"
  chapters:
    - index.qmd
    - notation.qmd
    - global-nonlinear.qmd
    - finite-dynamics.qmd
    - gaussian-calculus.qmd
    - arctan-limits.qmd
    - special-data-limits.qmd
    - linear-dynamics.qmd
    - continuous-depth.qmd
    - finite-optimization-and-controls.qmd
    - observable-p1.qmd

bibliography: references.bib

number-sections: false
crossref:
  chapters: false

classoption: enabledeprecatedfontcommands
header-includes:
  - \usepackage{mathtools}
  - \usepackage{fvextra}
  - \RecustomVerbatimEnvironment{verbatim}{Verbatim}{breaklines=true,breakanywhere=true}
  - \AtBeginDocument{\counterwithout{equation}{chapter}\counterwithout{theorem}{section}\counterwithout{lemma}{section}\counterwithout{proposition}{section}\counterwithout{corollary}{section}}
format:
  html: default
  pdf:
    pdf-engine: xelatex
    keep-tex: true
    latex-auto-install: false
    latex-tinytex: false
    filters:
      - pdf_breakable_tables.lua
  latex:
    filters:
      - pdf_breakable_tables.lua
