"""Independent finite-width audit of the genuinely joint H=3, B=2 GNF.

The Gaussian target is the exact rational fixture in
``DEPTH_FIXED_BATCH_GAUSSIAN_RECURSION.md``.  Samples are generated by the exact
finite-width moving feature-ascent compiler.  The frozen-line third
derivative below is computed independently, directly from the initial
gradient and ordinary polynomial series; the Hessian-square sample is then
recovered from the exact identity ``D_c^3 g_c = 2 T_c + 4 H_c``.

This is a statistical convergence gate, not part of the proof.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
from math import factorial, sqrt

import numpy as np

from .finite_width_jet import feature_ascent_jet
from .model import DepthState, sample_state
from .raw_coordinate_jet_audit import raw_coordinate_derivatives


INPUT_GRAM = np.asarray([[1.0, 1.0 / 3.0], [1.0 / 3.0, 4.0 / 3.0]])
CHANNEL = np.asarray([2.0 / 3.0, -1.0 / 4.0])
TARGET_A = float(Fraction(307537184532813623, 164025000000000000))
TARGET_T = float(
    Fraction(
        11643944742979081152864841261859587,
        10089075234375000000000000000000000,
    )
)
TARGET_H = float(
    Fraction(
        87519639501953069352749665519602563,
        6726050156250000000000000000000000,
    )
)
TARGET_C = float(
    Fraction(
        68550715812209572302778459455166819,
        1261134404296875000000000000000000,
    )
)


def quadratic_perturbation_derivative(order: int, x: np.ndarray) -> np.ndarray:
    """Derivatives of ``phi(x)=x+x^2/10`` through the needed order."""

    if order == 0:
        return x + x * x / 10.0
    if order == 1:
        return 1.0 + x / 5.0
    if order == 2:
        return np.full_like(x, 1.0 / 5.0)
    return np.zeros_like(x)


def _convolve(left: np.ndarray, right: np.ndarray, degree: int) -> np.ndarray:
    return sum((left[r] * right[degree - r] for r in range(degree + 1)))


def _compose_quadratic(series: np.ndarray, degree: int) -> np.ndarray:
    return series[degree] + _convolve(series, series, degree) / 10.0


def frozen_third_derivative(
    state: DepthState,
    input_gram: np.ndarray = INPUT_GRAM,
    channel: np.ndarray = CHANNEL,
) -> float:
    """Compute ``d^3/ds^3 g(theta+s n grad g)|_0`` from raw arrays."""

    n = state.width
    hidden_layers = state.hidden_layers
    batch = state.batch
    if hidden_layers != 3 or batch != 2:
        raise ValueError("this hostile gate is fixed at H=3 and B=2")
    inverse_sqrt_width = 1.0 / sqrt(n)

    base_z = [state.first_preactivation]
    base_x = [quadratic_perturbation_derivative(0, base_z[0])]
    for weight in state.hidden_weights:
        base_z.append(inverse_sqrt_width * (weight @ base_x[-1]))
        base_x.append(quadratic_perturbation_derivative(0, base_z[-1]))

    reverse = [np.zeros((n, batch)) for _ in range(hidden_layers)]
    source = [np.zeros((n, batch)) for _ in range(hidden_layers)]
    source[-1] = (
        state.readout[:, None]
        * quadratic_perturbation_derivative(1, base_z[-1])
        * channel[None, :]
    )
    for layer in range(hidden_layers - 2, -1, -1):
        reverse[layer] = (
            inverse_sqrt_width
            * state.hidden_weights[layer].T
            @ source[layer + 1]
        )
        source[layer] = (
            quadratic_perturbation_derivative(1, base_z[layer])
            * reverse[layer]
        )

    readout_dot = base_x[-1] @ channel
    weight_dot = [
        inverse_sqrt_width * source[layer] @ base_x[layer - 1].T
        for layer in range(1, hidden_layers)
    ]

    z = [np.zeros((4, n, batch)) for _ in range(hidden_layers)]
    x = [np.zeros_like(value) for value in z]
    z[0][0] = base_z[0]
    z[0][1] = source[0] @ input_gram
    for degree in range(4):
        x[0][degree] = _compose_quadratic(z[0], degree)
        for layer in range(1, hidden_layers):
            coefficient = state.hidden_weights[layer - 1] @ x[layer - 1][degree]
            if degree:
                coefficient += weight_dot[layer - 1] @ x[layer - 1][degree - 1]
            z[layer][degree] = inverse_sqrt_width * coefficient
            x[layer][degree] = _compose_quadratic(z[layer], degree)

    third_ordinary = np.mean(
        state.readout * (x[-1][3] @ channel)
        + readout_dot * (x[-1][2] @ channel)
    )
    return factorial(3) * float(third_ordinary)


def _positive_integer_list(raw: str) -> tuple[int, ...]:
    values = tuple(int(value) for value in raw.split(","))
    if not values or any(value < 1 for value in values):
        raise argparse.ArgumentTypeError("expected comma-separated positive integers")
    return values


def _raw_coordinate_self_check() -> None:
    """Check the new frozen-series route against raw derivative tensors."""

    root = np.linalg.cholesky(INPUT_GRAM)
    inputs = sqrt(2.0) * root.T
    raw, state, recovered_gram, raw_frozen = raw_coordinate_derivatives(
        np.asarray([[0.37, -0.81]]),
        (np.asarray([[1.13]]), np.asarray([[-0.74]])),
        np.asarray([0.61]),
        inputs,
        CHANNEL,
        quadratic_perturbation_derivative,
    )
    compiled = feature_ascent_jet(
        state,
        recovered_gram,
        CHANNEL,
        quadratic_perturbation_derivative,
    ).derivatives
    np.testing.assert_allclose(compiled, raw, rtol=3.0e-12, atol=3.0e-12)
    np.testing.assert_allclose(
        frozen_third_derivative(state, recovered_gram, CHANNEL),
        raw_frozen,
        rtol=3.0e-12,
        atol=3.0e-12,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--widths", type=_positive_integer_list, default=(64, 128, 256, 512)
    )
    parser.add_argument(
        "--seeds", type=_positive_integer_list, default=(4000, 3000, 1200, 300)
    )
    parser.add_argument("--seed-base", type=int, default=947_000_000)
    args = parser.parse_args()
    if len(args.widths) != len(args.seeds):
        parser.error("--widths and --seeds must have the same number of entries")
    if len(args.widths) < 3:
        parser.error("the intercept audit needs at least three widths")
    if any(count < 2 for count in args.seeds):
        parser.error("every width needs at least two seeds")

    _raw_coordinate_self_check()

    print(
        f"targets A={TARGET_A:.12g} T={TARGET_T:.12g} "
        f"Hsq={TARGET_H:.12g} C={TARGET_C:.12g}"
    )
    rows: list[tuple[int, np.ndarray, np.ndarray]] = []
    for width, count in zip(args.widths, args.seeds):
        samples = np.empty((count, 4))
        for index in range(count):
            state = sample_state(
                width,
                INPUT_GRAM,
                hidden_layers=3,
                seed=args.seed_base + width * 100_000 + index,
            )
            moving_jet = feature_ascent_jet(
                state,
                INPUT_GRAM,
                CHANNEL,
                quadratic_perturbation_derivative,
            ).derivatives
            ntk = moving_jet[1]
            correction = moving_jet[3]
            straight = frozen_third_derivative(state)
            hessian_square = (correction - 2.0 * straight) / 4.0
            samples[index] = (ntk, straight, hessian_square, correction)
        mean = samples.mean(axis=0)
        error = samples.std(axis=0, ddof=1) / sqrt(count)
        rows.append((width, mean, error))
        print(
            f"n={width:4d} seeds={count:5d} "
            f"A={mean[0]:.10g}+/-{error[0]:.4g} "
            f"T={mean[1]:.10g}+/-{error[1]:.4g} "
            f"H={mean[2]:.10g}+/-{error[2]:.4g} "
            f"C={mean[3]:.10g}+/-{error[3]:.4g}"
        )

    targets = np.asarray([TARGET_A, TARGET_T, TARGET_H, TARGET_C])
    inverse_width = np.asarray([1.0 / row[0] for row in rows])
    design = np.column_stack((np.ones_like(inverse_width), inverse_width))
    for coordinate, name in enumerate(("A", "T", "H", "C")):
        means = np.asarray([row[1][coordinate] for row in rows])
        errors = np.asarray([row[2][coordinate] for row in rows])
        precision = np.diag(1.0 / errors**2)
        covariance = np.linalg.inv(design.T @ precision @ design)
        coefficients = covariance @ design.T @ precision @ means
        intercept_error = sqrt(float(covariance[0, 0]))
        z_score = (float(coefficients[0]) - targets[coordinate]) / intercept_error
        residual = means - design @ coefficients
        chi_square_per_dof = float(
            residual @ precision @ residual / (len(rows) - design.shape[1])
        )
        print(
            f"{name} weighted 1/n intercept={coefficients[0]:.12g} "
            f"+/-{intercept_error:.5g}, target-z={z_score:.4f}, "
            f"chi2/dof={chi_square_per_dof:.5g}"
        )


if __name__ == "__main__":
    main()
