#!/usr/bin/env python3
"""Protect dollar-delimited mathematics from the legacy TeX Markdown parser.

The TeX Live 2022 markdown package available in the workspace predates native
support for dollar math.  This build helper replaces each math span by a small
raw-TeX placeholder and emits a companion file containing the exact math.  It
does not alter the maintained Markdown sources.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SOURCE_DIR / "build" / "markdown"
SOURCES = [
    "MEAN_FIELD_PEELING_PROGRAM.md",
    "MUP_TRAINING_PEELING_CASE_STUDY.md",
    "TENSOR_PROGRAMS_CONTRAST_AND_THEOREM_FRAMING_REPORT.md",
]


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    mathematics: list[tuple[str, str]] = []

    def register(kind: str, body: str) -> str:
        mathematics.append((kind, body.strip()))
        return rf"\MFMath{{{len(mathematics)}}}"

    # A display delimiter occupies its own Markdown line in the maintained
    # sources.  Preserve indentation so displays nested in lists remain nested.
    display = re.compile(
        r"(?ms)^([ \t]*(?:>[ \t]*)?)\$\$[ \t]*\n?(.*?)\n?\1\$\$[ \t]*$"
    )
    inline = re.compile(r"(?<!\\)\$(?!\$)(.+?)(?<!\\)\$(?!\$)")

    for source_name in SOURCES:
        source = (SOURCE_DIR / source_name).read_text(encoding="utf-8")

        def replace_display(match: re.Match[str]) -> str:
            prefix, body = match.group(1), match.group(2)
            # Markdown block quotes repeat their `> ` prefix on every line.
            # Remove it from the protected TeX body, but retain it on the
            # placeholder so the display stays inside the quotation.
            if ">" in prefix:
                body = "\n".join(
                    line[len(prefix) :] if line.startswith(prefix) else line
                    for line in body.splitlines()
                )
            return prefix + register("display", body)

        protected = display.sub(replace_display, source)
        protected = inline.sub(
            lambda match: register("inline", match.group(1)), protected
        )
        output_name = source_name.removesuffix(".md") + ".pdf.md"
        (OUTPUT_DIR / output_name).write_text(protected, encoding="utf-8")

    definitions = [
        "% Generated by render_markdown_math.py; do not edit.",
        r"\newcommand{\MFMath}[1]{\csname MFmath#1\endcsname}",
    ]
    for index, (kind, body) in enumerate(mathematics, start=1):
        # Hash marks have parameter meaning inside a macro definition.  They do
        # not occur structurally in the mathematical sources; escape any that
        # appear as literal mathematical characters.
        body = body.replace("#", r"\#")
        if kind == "display":
            rendered = "\\[\n" + body + "\n\\]"
        else:
            rendered = r"\ensuremath{" + body + "}"
        definitions.append(
            rf"\expandafter\def\csname MFmath{index}\endcsname{{{rendered}}}"
        )

    (OUTPUT_DIR / "markdown_math_defs.tex").write_text(
        "\n".join(definitions) + "\n", encoding="utf-8"
    )
    print(f"Protected {len(mathematics)} math spans from {len(SOURCES)} sources.")


if __name__ == "__main__":
    main()
